"""
final words(NOTE: READ THESE AFTER U GO THROUGH ALL BELOW LINES AND CODE)
1)copy() funtion will create a copy of an array and stores in a var if specified.it owns the data means the data is its own once copies.
2)view() function is like it just views the data it doesnt own the data.if the value in the original array changes then the values in the array created using view() also changes
"""

checking whether values of arrays created using copy() and view()  changes if we change value of original array

In [19]:
import numpy as np
x=np.array([1,2,3,4])
print("array before:")
print(x)
#using copy and view
y=x.copy()
z=x.view()
x[0]=9
print("array after modification")
print(y)#the values of y doesnt changes as y owns the array values it wont be displaying values array values of x
print(z)#the values of z changes as z doesnt owns the array values it will be displaying the values of array x 


array before:
[1 2 3 4]
array after modification
[1 2 3 4]
[9 2 3 4]


checking in reverse manner of above checking whether original array values changes if we change in array created using copy() and view() function

In [27]:
x=np.array([1,2,3,4])
y=x.copy()
z=x.view()
print("all arrays before any modifications")
print("x=",x)
print("y=",y)
print("z=",z)
y[0]=9
print("after modification in y which is array created using copy() function")
print("x=",x)
print("y=",y)
print("z=",z)
z[1]=8
print("after modification in z which is array created using view function")
print("x=",x)
print("y=",y)
print("z=",z)

all arrays before any modifications
x= [1 2 3 4]
y= [1 2 3 4]
z= [1 2 3 4]
after modification in y which is array created using copy() function
x= [1 2 3 4]
y= [9 2 3 4]
z= [1 2 3 4]
after modification in z which is array created using view function
x= [1 8 3 4]
y= [9 2 3 4]
z= [1 8 3 4]
