# joining arrays using concatenate operation

concatenate on 1d arrays #BIGNOTE while concatenating u should us np.concatenate((a,b)) not np.concatenate(a,b)

In [6]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(np.concatenate((a,b)))

[5 7 9]
[1 2 3 4 5 6]


concatenating 2d arrays

In [38]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
c=np.concatenate((a,b))
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


joining 2d arrays along rows(what happens here is the 1st rows of two matrices will be joined and 2nd rows of two matrices are also joined

In [45]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
c=np.concatenate((a,b),axis=1)
d=np.concatenate((a,b),axis=0)
print("while passing axis=1 i.e., axis=True")
print(c)
print("while passing axis=1 i.e., axis=False")
print(d)

while passing axis=1 i.e., axis=True
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
while passing axis=1 i.e., axis=False
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


concatenating 3d arrays

In [46]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
b=np.array([[[111,222,333],[444,555,666]],[[777,888,999],[100,110,120]]])
print(np.concatenate((a,b)))

[[[  1   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 10  11  12]]

 [[111 222 333]
  [444 555 666]]

 [[777 888 999]
  [100 110 120]]]


In [48]:
print(np.concatenate((a,b),axis=1))#here what happens is the 3d arrays are concatenaed along matrices the first matrices of two cubes are joined or concatenated and the second two matrices of two cubes are joined or concatenated

[[[  1   2   3]
  [  4   5   6]
  [111 222 333]
  [444 555 666]]

 [[  7   8   9]
  [ 10  11  12]
  [777 888 999]
  [100 110 120]]]


some experimental stuff

In [34]:
from numpy import concatenate as c
a=np.array([1,2,3])
b=np.array([7,8,9])
k=c((a,b))
j=np.concatenate((a,b))
print(k)
print(j)

[1 2 3 7 8 9]
[1 2 3 7 8 9]


what if we try to concatenate ndarrays of different dimensions

In [37]:
a=np.array([1,2,3])
b=np.array([[7,8,9],[4,5,6]])
c=np.concatenate((a,b))#the output will be like u cant add arrays of two different dimensions

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [ ]:
NOTE :I LEFT THE TOPIC JOINING ARRAYS USING STACK TO AVOID CONFUSION